import sqlite3

def generate_analytics_report():
    # 1. Establish connection to the historical database generated by the pipeline
    conn = sqlite3.connect('weather_history.db')
    cursor = conn.cursor()

    # 2. Analytical transform query evaluating metrics against contextual baseline averages
    query = """
    SELECT 
        t1.City, 
        t1.Temperature as Current_Temp, 
        ROUND(t2.Avg_Temp, 2) as Avg_Temp,
        ROUND((t1.Temperature - t2.Avg_Temp), 2) as Diff
    FROM daily_weather t1

    -- Join: Map baseline averages segmented by location and dynamic time period (Day/Night)
    JOIN (
        SELECT City, 
               CASE WHEN strftime('%H', Timestamp) >= '06' AND strftime('%H', Timestamp) < '18' 
                    THEN 'Day' ELSE 'Night' END as Time_Period,
               AVG(Temperature) as Avg_Temp
        FROM daily_weather
        GROUP BY 1, 2
    ) t2 ON t1.City = t2.City 
       AND t2.Time_Period = (CASE WHEN strftime('%H', 'now', 'localtime') >= '06' 
                                  AND strftime('%H', 'now', 'localtime') < '18' 
                                  THEN 'Day' ELSE 'Night' END)

    -- Filter: Isolate exclusively the latest telemetry capture for each unique city
    WHERE t1.Timestamp = (SELECT MAX(Timestamp) FROM daily_weather WHERE City = t1.City)

    -- Order: Sort dataset by severity of calculated temperature anomalies
    ORDER BY Diff DESC;
    """

    try:
        # 3. Execute analytics query using pure database cursor
        cursor.execute(query)
        rows = cursor.fetchall()
        
        print("\n=======================================================")
        print("          📊 WEATHER SUMMARY & ANOMALY REPORT     ")
        print("=======================================================")
        print(f"{'City':<15} | {'Current Temp':<12} | {'Avg Temp':<10} | {'Deviation':<10}")
        print("-" * 55)
        
        if rows:
            for row in rows:
                print(f"{row[0]:<15} | {row[1]:<12} | {row[2]:<10} | {row[3]:+10}")
        else:
            print("No data found. Please ensure the pipeline has populated the database.")
        print("=======================================================\n")
        
    except Exception as e:
        print(f"Error executing analytics query: {e}")
        
    finally:
        # 4. Gracefully terminate database connection lifecycle
        conn.close()

if __name__ == "__main__":
    generate_analytics_report()